#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokoSinar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TokoSinar")]
	public partial class TokoSinarDB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbSupplier(tbSupplier instance);
    partial void UpdatetbSupplier(tbSupplier instance);
    partial void DeletetbSupplier(tbSupplier instance);
    partial void InserttbBarang(tbBarang instance);
    partial void UpdatetbBarang(tbBarang instance);
    partial void DeletetbBarang(tbBarang instance);
    partial void InserttbDetailPembelian(tbDetailPembelian instance);
    partial void UpdatetbDetailPembelian(tbDetailPembelian instance);
    partial void DeletetbDetailPembelian(tbDetailPembelian instance);
    partial void InserttbDetailPenjualan(tbDetailPenjualan instance);
    partial void UpdatetbDetailPenjualan(tbDetailPenjualan instance);
    partial void DeletetbDetailPenjualan(tbDetailPenjualan instance);
    partial void InserttbDetailRetur(tbDetailRetur instance);
    partial void UpdatetbDetailRetur(tbDetailRetur instance);
    partial void DeletetbDetailRetur(tbDetailRetur instance);
    partial void InserttbKaryawan(tbKaryawan instance);
    partial void UpdatetbKaryawan(tbKaryawan instance);
    partial void DeletetbKaryawan(tbKaryawan instance);
    partial void InserttbPembelian(tbPembelian instance);
    partial void UpdatetbPembelian(tbPembelian instance);
    partial void DeletetbPembelian(tbPembelian instance);
    partial void InserttbPenjualan(tbPenjualan instance);
    partial void UpdatetbPenjualan(tbPenjualan instance);
    partial void DeletetbPenjualan(tbPenjualan instance);
    partial void InserttbRetur(tbRetur instance);
    partial void UpdatetbRetur(tbRetur instance);
    partial void DeletetbRetur(tbRetur instance);
    partial void InserttbRole(tbRole instance);
    partial void UpdatetbRole(tbRole instance);
    partial void DeletetbRole(tbRole instance);
    #endregion
		
		public TokoSinarDB() : 
				base(global::TokoSinar.Properties.Settings.Default.TokoSinarConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TokoSinarDB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TokoSinarDB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TokoSinarDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TokoSinarDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ViewReportInventori> ViewReportInventoris
		{
			get
			{
				return this.GetTable<ViewReportInventori>();
			}
		}
		
		public System.Data.Linq.Table<ViewReportPenjualan> ViewReportPenjualans
		{
			get
			{
				return this.GetTable<ViewReportPenjualan>();
			}
		}
		
		public System.Data.Linq.Table<ViewReportPembelian> ViewReportPembelians
		{
			get
			{
				return this.GetTable<ViewReportPembelian>();
			}
		}
		
		public System.Data.Linq.Table<tbSupplier> tbSuppliers
		{
			get
			{
				return this.GetTable<tbSupplier>();
			}
		}
		
		public System.Data.Linq.Table<tbBarang> tbBarangs
		{
			get
			{
				return this.GetTable<tbBarang>();
			}
		}
		
		public System.Data.Linq.Table<tbDetailPembelian> tbDetailPembelians
		{
			get
			{
				return this.GetTable<tbDetailPembelian>();
			}
		}
		
		public System.Data.Linq.Table<tbDetailPenjualan> tbDetailPenjualans
		{
			get
			{
				return this.GetTable<tbDetailPenjualan>();
			}
		}
		
		public System.Data.Linq.Table<tbDetailRetur> tbDetailReturs
		{
			get
			{
				return this.GetTable<tbDetailRetur>();
			}
		}
		
		public System.Data.Linq.Table<tbKaryawan> tbKaryawans
		{
			get
			{
				return this.GetTable<tbKaryawan>();
			}
		}
		
		public System.Data.Linq.Table<tbPembelian> tbPembelians
		{
			get
			{
				return this.GetTable<tbPembelian>();
			}
		}
		
		public System.Data.Linq.Table<tbPenjualan> tbPenjualans
		{
			get
			{
				return this.GetTable<tbPenjualan>();
			}
		}
		
		public System.Data.Linq.Table<tbRetur> tbReturs
		{
			get
			{
				return this.GetTable<tbRetur>();
			}
		}
		
		public System.Data.Linq.Table<tbRole> tbRoles
		{
			get
			{
				return this.GetTable<tbRole>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AutoIDBarang")]
		public int SP_AutoIDBarang()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AutoIDSupplier")]
		public int SP_AutoIDSupplier()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AutoIDPenjualan")]
		public int SP_AutoIDPenjualan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AutoIDRetur")]
		public int SP_AutoIDRetur()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FC_AutoIDBarang", IsComposable=true)]
		public string FC_AutoIDBarang()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FC_AutoIDSupplier", IsComposable=true)]
		public string FC_AutoIDSupplier()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FC_AutoIDPenjualan", IsComposable=true)]
		public string FC_AutoIDPenjualan()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FC_AutoIDRetur", IsComposable=true)]
		public string FC_AutoIDRetur()
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewReportInventori")]
	public partial class ViewReportInventori
	{
		
		private string _ID_Barang;
		
		private string _Nama_Barang;
		
		private System.Nullable<decimal> _Harga_Beli;
		
		private System.Nullable<decimal> _Harga_Jual;
		
		private string _Satuan;
		
		private System.Nullable<int> _Stok;
		
		private string _Nama_Supplier;
		
		public ViewReportInventori()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Barang", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Barang
		{
			get
			{
				return this._ID_Barang;
			}
			set
			{
				if ((this._ID_Barang != value))
				{
					this._ID_Barang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Barang", DbType="NVarChar(50)")]
		public string Nama_Barang
		{
			get
			{
				return this._Nama_Barang;
			}
			set
			{
				if ((this._Nama_Barang != value))
				{
					this._Nama_Barang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Beli", DbType="Money")]
		public System.Nullable<decimal> Harga_Beli
		{
			get
			{
				return this._Harga_Beli;
			}
			set
			{
				if ((this._Harga_Beli != value))
				{
					this._Harga_Beli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Jual", DbType="Money")]
		public System.Nullable<decimal> Harga_Jual
		{
			get
			{
				return this._Harga_Jual;
			}
			set
			{
				if ((this._Harga_Jual != value))
				{
					this._Harga_Jual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Satuan", DbType="NVarChar(10)")]
		public string Satuan
		{
			get
			{
				return this._Satuan;
			}
			set
			{
				if ((this._Satuan != value))
				{
					this._Satuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok", DbType="Int")]
		public System.Nullable<int> Stok
		{
			get
			{
				return this._Stok;
			}
			set
			{
				if ((this._Stok != value))
				{
					this._Stok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Supplier", DbType="NVarChar(50)")]
		public string Nama_Supplier
		{
			get
			{
				return this._Nama_Supplier;
			}
			set
			{
				if ((this._Nama_Supplier != value))
				{
					this._Nama_Supplier = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewReportPenjualan")]
	public partial class ViewReportPenjualan
	{
		
		private string _ID_Penjualan;
		
		private System.Nullable<System.DateTime> _Tanggal_Penjualan;
		
		private string _Nama_Barang;
		
		private System.Nullable<decimal> _Harga_Jual;
		
		private System.Nullable<int> _Jumlah_Jual;
		
		private System.Nullable<decimal> _Sub_Total;
		
		private System.Nullable<decimal> _Total_Penjualan;
		
		private string _Username;
		
		public ViewReportPenjualan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Penjualan", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Penjualan
		{
			get
			{
				return this._ID_Penjualan;
			}
			set
			{
				if ((this._ID_Penjualan != value))
				{
					this._ID_Penjualan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal_Penjualan", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tanggal_Penjualan
		{
			get
			{
				return this._Tanggal_Penjualan;
			}
			set
			{
				if ((this._Tanggal_Penjualan != value))
				{
					this._Tanggal_Penjualan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Barang", DbType="NVarChar(50)")]
		public string Nama_Barang
		{
			get
			{
				return this._Nama_Barang;
			}
			set
			{
				if ((this._Nama_Barang != value))
				{
					this._Nama_Barang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Jual", DbType="Money")]
		public System.Nullable<decimal> Harga_Jual
		{
			get
			{
				return this._Harga_Jual;
			}
			set
			{
				if ((this._Harga_Jual != value))
				{
					this._Harga_Jual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah_Jual", DbType="Int")]
		public System.Nullable<int> Jumlah_Jual
		{
			get
			{
				return this._Jumlah_Jual;
			}
			set
			{
				if ((this._Jumlah_Jual != value))
				{
					this._Jumlah_Jual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="Money")]
		public System.Nullable<decimal> Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this._Sub_Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Penjualan", DbType="Money")]
		public System.Nullable<decimal> Total_Penjualan
		{
			get
			{
				return this._Total_Penjualan;
			}
			set
			{
				if ((this._Total_Penjualan != value))
				{
					this._Total_Penjualan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(15)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewReportPembelian")]
	public partial class ViewReportPembelian
	{
		
		private string _No_Faktur;
		
		private System.Nullable<System.DateTime> _Tanggal_Pembelian;
		
		private string _CaraBayar;
		
		private string _Salesman;
		
		private System.Nullable<System.DateTime> _JatuhTempo;
		
		private System.Nullable<decimal> _Harga_Beli;
		
		private System.Nullable<int> _Jumlah_Beli;
		
		private System.Nullable<decimal> _Sub_Total;
		
		private System.Nullable<double> _PPN;
		
		private System.Nullable<decimal> _Total_Pembelian;
		
		private string _Nama_Barang;
		
		private string _Nama_Supplier;
		
		public ViewReportPembelian()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Faktur", DbType="NVarChar(20)")]
		public string No_Faktur
		{
			get
			{
				return this._No_Faktur;
			}
			set
			{
				if ((this._No_Faktur != value))
				{
					this._No_Faktur = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal_Pembelian", DbType="Date")]
		public System.Nullable<System.DateTime> Tanggal_Pembelian
		{
			get
			{
				return this._Tanggal_Pembelian;
			}
			set
			{
				if ((this._Tanggal_Pembelian != value))
				{
					this._Tanggal_Pembelian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaraBayar", DbType="NVarChar(50)")]
		public string CaraBayar
		{
			get
			{
				return this._CaraBayar;
			}
			set
			{
				if ((this._CaraBayar != value))
				{
					this._CaraBayar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salesman", DbType="NVarChar(50)")]
		public string Salesman
		{
			get
			{
				return this._Salesman;
			}
			set
			{
				if ((this._Salesman != value))
				{
					this._Salesman = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JatuhTempo", DbType="Date")]
		public System.Nullable<System.DateTime> JatuhTempo
		{
			get
			{
				return this._JatuhTempo;
			}
			set
			{
				if ((this._JatuhTempo != value))
				{
					this._JatuhTempo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Beli", DbType="Money")]
		public System.Nullable<decimal> Harga_Beli
		{
			get
			{
				return this._Harga_Beli;
			}
			set
			{
				if ((this._Harga_Beli != value))
				{
					this._Harga_Beli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah_Beli", DbType="Int")]
		public System.Nullable<int> Jumlah_Beli
		{
			get
			{
				return this._Jumlah_Beli;
			}
			set
			{
				if ((this._Jumlah_Beli != value))
				{
					this._Jumlah_Beli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="Money")]
		public System.Nullable<decimal> Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this._Sub_Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPN", DbType="Float")]
		public System.Nullable<double> PPN
		{
			get
			{
				return this._PPN;
			}
			set
			{
				if ((this._PPN != value))
				{
					this._PPN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Pembelian", DbType="Money")]
		public System.Nullable<decimal> Total_Pembelian
		{
			get
			{
				return this._Total_Pembelian;
			}
			set
			{
				if ((this._Total_Pembelian != value))
				{
					this._Total_Pembelian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Barang", DbType="NVarChar(50)")]
		public string Nama_Barang
		{
			get
			{
				return this._Nama_Barang;
			}
			set
			{
				if ((this._Nama_Barang != value))
				{
					this._Nama_Barang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Supplier", DbType="NVarChar(50)")]
		public string Nama_Supplier
		{
			get
			{
				return this._Nama_Supplier;
			}
			set
			{
				if ((this._Nama_Supplier != value))
				{
					this._Nama_Supplier = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSupplier")]
	public partial class tbSupplier : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Supplier;
		
		private string _Nama_Supplier;
		
		private string _Alamat_Supplier;
		
		private string _No_TelponSupplier;
		
		private string _Status;
		
		private EntitySet<tbBarang> _tbBarangs;
		
		private EntitySet<tbPembelian> _tbPembelians;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SupplierChanging(string value);
    partial void OnID_SupplierChanged();
    partial void OnNama_SupplierChanging(string value);
    partial void OnNama_SupplierChanged();
    partial void OnAlamat_SupplierChanging(string value);
    partial void OnAlamat_SupplierChanged();
    partial void OnNo_TelponSupplierChanging(string value);
    partial void OnNo_TelponSupplierChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public tbSupplier()
		{
			this._tbBarangs = new EntitySet<tbBarang>(new Action<tbBarang>(this.attach_tbBarangs), new Action<tbBarang>(this.detach_tbBarangs));
			this._tbPembelians = new EntitySet<tbPembelian>(new Action<tbPembelian>(this.attach_tbPembelians), new Action<tbPembelian>(this.detach_tbPembelians));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Supplier", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Supplier
		{
			get
			{
				return this._ID_Supplier;
			}
			set
			{
				if ((this._ID_Supplier != value))
				{
					this.OnID_SupplierChanging(value);
					this.SendPropertyChanging();
					this._ID_Supplier = value;
					this.SendPropertyChanged("ID_Supplier");
					this.OnID_SupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Supplier", DbType="NVarChar(50)")]
		public string Nama_Supplier
		{
			get
			{
				return this._Nama_Supplier;
			}
			set
			{
				if ((this._Nama_Supplier != value))
				{
					this.OnNama_SupplierChanging(value);
					this.SendPropertyChanging();
					this._Nama_Supplier = value;
					this.SendPropertyChanged("Nama_Supplier");
					this.OnNama_SupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat_Supplier", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Alamat_Supplier
		{
			get
			{
				return this._Alamat_Supplier;
			}
			set
			{
				if ((this._Alamat_Supplier != value))
				{
					this.OnAlamat_SupplierChanging(value);
					this.SendPropertyChanging();
					this._Alamat_Supplier = value;
					this.SendPropertyChanged("Alamat_Supplier");
					this.OnAlamat_SupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_TelponSupplier", DbType="NVarChar(15)")]
		public string No_TelponSupplier
		{
			get
			{
				return this._No_TelponSupplier;
			}
			set
			{
				if ((this._No_TelponSupplier != value))
				{
					this.OnNo_TelponSupplierChanging(value);
					this.SendPropertyChanging();
					this._No_TelponSupplier = value;
					this.SendPropertyChanged("No_TelponSupplier");
					this.OnNo_TelponSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSupplier_tbBarang", Storage="_tbBarangs", ThisKey="ID_Supplier", OtherKey="ID_Supplier")]
		public EntitySet<tbBarang> tbBarangs
		{
			get
			{
				return this._tbBarangs;
			}
			set
			{
				this._tbBarangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSupplier_tbPembelian", Storage="_tbPembelians", ThisKey="ID_Supplier", OtherKey="ID_Supplier")]
		public EntitySet<tbPembelian> tbPembelians
		{
			get
			{
				return this._tbPembelians;
			}
			set
			{
				this._tbPembelians.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbBarangs(tbBarang entity)
		{
			this.SendPropertyChanging();
			entity.tbSupplier = this;
		}
		
		private void detach_tbBarangs(tbBarang entity)
		{
			this.SendPropertyChanging();
			entity.tbSupplier = null;
		}
		
		private void attach_tbPembelians(tbPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbSupplier = this;
		}
		
		private void detach_tbPembelians(tbPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbSupplier = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbBarang")]
	public partial class tbBarang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Barang;
		
		private string _Nama_Barang;
		
		private System.Nullable<decimal> _Harga_Beli;
		
		private System.Nullable<decimal> _Harga_Jual;
		
		private string _Satuan;
		
		private System.Nullable<int> _Stok;
		
		private string _ID_Supplier;
		
		private EntitySet<tbDetailPembelian> _tbDetailPembelians;
		
		private EntitySet<tbDetailPenjualan> _tbDetailPenjualans;
		
		private EntitySet<tbDetailRetur> _tbDetailReturs;
		
		private EntityRef<tbSupplier> _tbSupplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BarangChanging(string value);
    partial void OnID_BarangChanged();
    partial void OnNama_BarangChanging(string value);
    partial void OnNama_BarangChanged();
    partial void OnHarga_BeliChanging(System.Nullable<decimal> value);
    partial void OnHarga_BeliChanged();
    partial void OnHarga_JualChanging(System.Nullable<decimal> value);
    partial void OnHarga_JualChanged();
    partial void OnSatuanChanging(string value);
    partial void OnSatuanChanged();
    partial void OnStokChanging(System.Nullable<int> value);
    partial void OnStokChanged();
    partial void OnID_SupplierChanging(string value);
    partial void OnID_SupplierChanged();
    #endregion
		
		public tbBarang()
		{
			this._tbDetailPembelians = new EntitySet<tbDetailPembelian>(new Action<tbDetailPembelian>(this.attach_tbDetailPembelians), new Action<tbDetailPembelian>(this.detach_tbDetailPembelians));
			this._tbDetailPenjualans = new EntitySet<tbDetailPenjualan>(new Action<tbDetailPenjualan>(this.attach_tbDetailPenjualans), new Action<tbDetailPenjualan>(this.detach_tbDetailPenjualans));
			this._tbDetailReturs = new EntitySet<tbDetailRetur>(new Action<tbDetailRetur>(this.attach_tbDetailReturs), new Action<tbDetailRetur>(this.detach_tbDetailReturs));
			this._tbSupplier = default(EntityRef<tbSupplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Barang", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Barang
		{
			get
			{
				return this._ID_Barang;
			}
			set
			{
				if ((this._ID_Barang != value))
				{
					this.OnID_BarangChanging(value);
					this.SendPropertyChanging();
					this._ID_Barang = value;
					this.SendPropertyChanged("ID_Barang");
					this.OnID_BarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Barang", DbType="NVarChar(50)")]
		public string Nama_Barang
		{
			get
			{
				return this._Nama_Barang;
			}
			set
			{
				if ((this._Nama_Barang != value))
				{
					this.OnNama_BarangChanging(value);
					this.SendPropertyChanging();
					this._Nama_Barang = value;
					this.SendPropertyChanged("Nama_Barang");
					this.OnNama_BarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Beli", DbType="Money")]
		public System.Nullable<decimal> Harga_Beli
		{
			get
			{
				return this._Harga_Beli;
			}
			set
			{
				if ((this._Harga_Beli != value))
				{
					this.OnHarga_BeliChanging(value);
					this.SendPropertyChanging();
					this._Harga_Beli = value;
					this.SendPropertyChanged("Harga_Beli");
					this.OnHarga_BeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Jual", DbType="Money")]
		public System.Nullable<decimal> Harga_Jual
		{
			get
			{
				return this._Harga_Jual;
			}
			set
			{
				if ((this._Harga_Jual != value))
				{
					this.OnHarga_JualChanging(value);
					this.SendPropertyChanging();
					this._Harga_Jual = value;
					this.SendPropertyChanged("Harga_Jual");
					this.OnHarga_JualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Satuan", DbType="NVarChar(10)")]
		public string Satuan
		{
			get
			{
				return this._Satuan;
			}
			set
			{
				if ((this._Satuan != value))
				{
					this.OnSatuanChanging(value);
					this.SendPropertyChanging();
					this._Satuan = value;
					this.SendPropertyChanged("Satuan");
					this.OnSatuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok", DbType="Int")]
		public System.Nullable<int> Stok
		{
			get
			{
				return this._Stok;
			}
			set
			{
				if ((this._Stok != value))
				{
					this.OnStokChanging(value);
					this.SendPropertyChanging();
					this._Stok = value;
					this.SendPropertyChanged("Stok");
					this.OnStokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Supplier", DbType="NChar(10)")]
		public string ID_Supplier
		{
			get
			{
				return this._ID_Supplier;
			}
			set
			{
				if ((this._ID_Supplier != value))
				{
					if (this._tbSupplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SupplierChanging(value);
					this.SendPropertyChanging();
					this._ID_Supplier = value;
					this.SendPropertyChanged("ID_Supplier");
					this.OnID_SupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbBarang_tbDetailPembelian", Storage="_tbDetailPembelians", ThisKey="ID_Barang", OtherKey="ID_Barang")]
		public EntitySet<tbDetailPembelian> tbDetailPembelians
		{
			get
			{
				return this._tbDetailPembelians;
			}
			set
			{
				this._tbDetailPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbBarang_tbDetailPenjualan", Storage="_tbDetailPenjualans", ThisKey="ID_Barang", OtherKey="ID_Barang")]
		public EntitySet<tbDetailPenjualan> tbDetailPenjualans
		{
			get
			{
				return this._tbDetailPenjualans;
			}
			set
			{
				this._tbDetailPenjualans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbBarang_tbDetailRetur", Storage="_tbDetailReturs", ThisKey="ID_Barang", OtherKey="ID_Barang")]
		public EntitySet<tbDetailRetur> tbDetailReturs
		{
			get
			{
				return this._tbDetailReturs;
			}
			set
			{
				this._tbDetailReturs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSupplier_tbBarang", Storage="_tbSupplier", ThisKey="ID_Supplier", OtherKey="ID_Supplier", IsForeignKey=true)]
		public tbSupplier tbSupplier
		{
			get
			{
				return this._tbSupplier.Entity;
			}
			set
			{
				tbSupplier previousValue = this._tbSupplier.Entity;
				if (((previousValue != value) 
							|| (this._tbSupplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSupplier.Entity = null;
						previousValue.tbBarangs.Remove(this);
					}
					this._tbSupplier.Entity = value;
					if ((value != null))
					{
						value.tbBarangs.Add(this);
						this._ID_Supplier = value.ID_Supplier;
					}
					else
					{
						this._ID_Supplier = default(string);
					}
					this.SendPropertyChanged("tbSupplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetailPembelians(tbDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbBarang = this;
		}
		
		private void detach_tbDetailPembelians(tbDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbBarang = null;
		}
		
		private void attach_tbDetailPenjualans(tbDetailPenjualan entity)
		{
			this.SendPropertyChanging();
			entity.tbBarang = this;
		}
		
		private void detach_tbDetailPenjualans(tbDetailPenjualan entity)
		{
			this.SendPropertyChanging();
			entity.tbBarang = null;
		}
		
		private void attach_tbDetailReturs(tbDetailRetur entity)
		{
			this.SendPropertyChanging();
			entity.tbBarang = this;
		}
		
		private void detach_tbDetailReturs(tbDetailRetur entity)
		{
			this.SendPropertyChanging();
			entity.tbBarang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetailPembelian")]
	public partial class tbDetailPembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DetailPembelian;
		
		private string _Nama_Barang;
		
		private System.Nullable<decimal> _Harga_Beli;
		
		private System.Nullable<int> _Jumlah_Beli;
		
		private System.Nullable<double> _Diskon;
		
		private System.Nullable<decimal> _Sub_Total;
		
		private string _ID_Barang;
		
		private string _No_Faktur;
		
		private EntityRef<tbBarang> _tbBarang;
		
		private EntityRef<tbPembelian> _tbPembelian;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DetailPembelianChanging(int value);
    partial void OnID_DetailPembelianChanged();
    partial void OnNama_BarangChanging(string value);
    partial void OnNama_BarangChanged();
    partial void OnHarga_BeliChanging(System.Nullable<decimal> value);
    partial void OnHarga_BeliChanged();
    partial void OnJumlah_BeliChanging(System.Nullable<int> value);
    partial void OnJumlah_BeliChanged();
    partial void OnDiskonChanging(System.Nullable<double> value);
    partial void OnDiskonChanged();
    partial void OnSub_TotalChanging(System.Nullable<decimal> value);
    partial void OnSub_TotalChanged();
    partial void OnID_BarangChanging(string value);
    partial void OnID_BarangChanged();
    partial void OnNo_FakturChanging(string value);
    partial void OnNo_FakturChanged();
    #endregion
		
		public tbDetailPembelian()
		{
			this._tbBarang = default(EntityRef<tbBarang>);
			this._tbPembelian = default(EntityRef<tbPembelian>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DetailPembelian", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DetailPembelian
		{
			get
			{
				return this._ID_DetailPembelian;
			}
			set
			{
				if ((this._ID_DetailPembelian != value))
				{
					this.OnID_DetailPembelianChanging(value);
					this.SendPropertyChanging();
					this._ID_DetailPembelian = value;
					this.SendPropertyChanged("ID_DetailPembelian");
					this.OnID_DetailPembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Barang", DbType="NVarChar(50)")]
		public string Nama_Barang
		{
			get
			{
				return this._Nama_Barang;
			}
			set
			{
				if ((this._Nama_Barang != value))
				{
					this.OnNama_BarangChanging(value);
					this.SendPropertyChanging();
					this._Nama_Barang = value;
					this.SendPropertyChanged("Nama_Barang");
					this.OnNama_BarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Beli", DbType="Money")]
		public System.Nullable<decimal> Harga_Beli
		{
			get
			{
				return this._Harga_Beli;
			}
			set
			{
				if ((this._Harga_Beli != value))
				{
					this.OnHarga_BeliChanging(value);
					this.SendPropertyChanging();
					this._Harga_Beli = value;
					this.SendPropertyChanged("Harga_Beli");
					this.OnHarga_BeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah_Beli", DbType="Int")]
		public System.Nullable<int> Jumlah_Beli
		{
			get
			{
				return this._Jumlah_Beli;
			}
			set
			{
				if ((this._Jumlah_Beli != value))
				{
					this.OnJumlah_BeliChanging(value);
					this.SendPropertyChanging();
					this._Jumlah_Beli = value;
					this.SendPropertyChanged("Jumlah_Beli");
					this.OnJumlah_BeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diskon", DbType="Float")]
		public System.Nullable<double> Diskon
		{
			get
			{
				return this._Diskon;
			}
			set
			{
				if ((this._Diskon != value))
				{
					this.OnDiskonChanging(value);
					this.SendPropertyChanging();
					this._Diskon = value;
					this.SendPropertyChanged("Diskon");
					this.OnDiskonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="Money")]
		public System.Nullable<decimal> Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this.OnSub_TotalChanging(value);
					this.SendPropertyChanging();
					this._Sub_Total = value;
					this.SendPropertyChanged("Sub_Total");
					this.OnSub_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Barang", DbType="NChar(10)")]
		public string ID_Barang
		{
			get
			{
				return this._ID_Barang;
			}
			set
			{
				if ((this._ID_Barang != value))
				{
					if (this._tbBarang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_BarangChanging(value);
					this.SendPropertyChanging();
					this._ID_Barang = value;
					this.SendPropertyChanged("ID_Barang");
					this.OnID_BarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Faktur", DbType="NVarChar(20)")]
		public string No_Faktur
		{
			get
			{
				return this._No_Faktur;
			}
			set
			{
				if ((this._No_Faktur != value))
				{
					if (this._tbPembelian.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNo_FakturChanging(value);
					this.SendPropertyChanging();
					this._No_Faktur = value;
					this.SendPropertyChanged("No_Faktur");
					this.OnNo_FakturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbBarang_tbDetailPembelian", Storage="_tbBarang", ThisKey="ID_Barang", OtherKey="ID_Barang", IsForeignKey=true)]
		public tbBarang tbBarang
		{
			get
			{
				return this._tbBarang.Entity;
			}
			set
			{
				tbBarang previousValue = this._tbBarang.Entity;
				if (((previousValue != value) 
							|| (this._tbBarang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbBarang.Entity = null;
						previousValue.tbDetailPembelians.Remove(this);
					}
					this._tbBarang.Entity = value;
					if ((value != null))
					{
						value.tbDetailPembelians.Add(this);
						this._ID_Barang = value.ID_Barang;
					}
					else
					{
						this._ID_Barang = default(string);
					}
					this.SendPropertyChanged("tbBarang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPembelian_tbDetailPembelian", Storage="_tbPembelian", ThisKey="No_Faktur", OtherKey="No_Faktur", IsForeignKey=true)]
		public tbPembelian tbPembelian
		{
			get
			{
				return this._tbPembelian.Entity;
			}
			set
			{
				tbPembelian previousValue = this._tbPembelian.Entity;
				if (((previousValue != value) 
							|| (this._tbPembelian.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPembelian.Entity = null;
						previousValue.tbDetailPembelians.Remove(this);
					}
					this._tbPembelian.Entity = value;
					if ((value != null))
					{
						value.tbDetailPembelians.Add(this);
						this._No_Faktur = value.No_Faktur;
					}
					else
					{
						this._No_Faktur = default(string);
					}
					this.SendPropertyChanged("tbPembelian");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetailPenjualan")]
	public partial class tbDetailPenjualan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DetailPenjualan;
		
		private System.Nullable<decimal> _Harga_Jual;
		
		private System.Nullable<int> _Jumlah_Jual;
		
		private System.Nullable<decimal> _Sub_Total;
		
		private string _ID_Penjualan;
		
		private string _ID_Barang;
		
		private EntityRef<tbBarang> _tbBarang;
		
		private EntityRef<tbPenjualan> _tbPenjualan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DetailPenjualanChanging(int value);
    partial void OnID_DetailPenjualanChanged();
    partial void OnHarga_JualChanging(System.Nullable<decimal> value);
    partial void OnHarga_JualChanged();
    partial void OnJumlah_JualChanging(System.Nullable<int> value);
    partial void OnJumlah_JualChanged();
    partial void OnSub_TotalChanging(System.Nullable<decimal> value);
    partial void OnSub_TotalChanged();
    partial void OnID_PenjualanChanging(string value);
    partial void OnID_PenjualanChanged();
    partial void OnID_BarangChanging(string value);
    partial void OnID_BarangChanged();
    #endregion
		
		public tbDetailPenjualan()
		{
			this._tbBarang = default(EntityRef<tbBarang>);
			this._tbPenjualan = default(EntityRef<tbPenjualan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DetailPenjualan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DetailPenjualan
		{
			get
			{
				return this._ID_DetailPenjualan;
			}
			set
			{
				if ((this._ID_DetailPenjualan != value))
				{
					this.OnID_DetailPenjualanChanging(value);
					this.SendPropertyChanging();
					this._ID_DetailPenjualan = value;
					this.SendPropertyChanged("ID_DetailPenjualan");
					this.OnID_DetailPenjualanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Harga_Jual", DbType="Money")]
		public System.Nullable<decimal> Harga_Jual
		{
			get
			{
				return this._Harga_Jual;
			}
			set
			{
				if ((this._Harga_Jual != value))
				{
					this.OnHarga_JualChanging(value);
					this.SendPropertyChanging();
					this._Harga_Jual = value;
					this.SendPropertyChanged("Harga_Jual");
					this.OnHarga_JualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah_Jual", DbType="Int")]
		public System.Nullable<int> Jumlah_Jual
		{
			get
			{
				return this._Jumlah_Jual;
			}
			set
			{
				if ((this._Jumlah_Jual != value))
				{
					this.OnJumlah_JualChanging(value);
					this.SendPropertyChanging();
					this._Jumlah_Jual = value;
					this.SendPropertyChanged("Jumlah_Jual");
					this.OnJumlah_JualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="Money")]
		public System.Nullable<decimal> Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this.OnSub_TotalChanging(value);
					this.SendPropertyChanging();
					this._Sub_Total = value;
					this.SendPropertyChanged("Sub_Total");
					this.OnSub_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Penjualan", DbType="NChar(10)")]
		public string ID_Penjualan
		{
			get
			{
				return this._ID_Penjualan;
			}
			set
			{
				if ((this._ID_Penjualan != value))
				{
					if (this._tbPenjualan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PenjualanChanging(value);
					this.SendPropertyChanging();
					this._ID_Penjualan = value;
					this.SendPropertyChanged("ID_Penjualan");
					this.OnID_PenjualanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Barang", DbType="NChar(10)")]
		public string ID_Barang
		{
			get
			{
				return this._ID_Barang;
			}
			set
			{
				if ((this._ID_Barang != value))
				{
					if (this._tbBarang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_BarangChanging(value);
					this.SendPropertyChanging();
					this._ID_Barang = value;
					this.SendPropertyChanged("ID_Barang");
					this.OnID_BarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbBarang_tbDetailPenjualan", Storage="_tbBarang", ThisKey="ID_Barang", OtherKey="ID_Barang", IsForeignKey=true)]
		public tbBarang tbBarang
		{
			get
			{
				return this._tbBarang.Entity;
			}
			set
			{
				tbBarang previousValue = this._tbBarang.Entity;
				if (((previousValue != value) 
							|| (this._tbBarang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbBarang.Entity = null;
						previousValue.tbDetailPenjualans.Remove(this);
					}
					this._tbBarang.Entity = value;
					if ((value != null))
					{
						value.tbDetailPenjualans.Add(this);
						this._ID_Barang = value.ID_Barang;
					}
					else
					{
						this._ID_Barang = default(string);
					}
					this.SendPropertyChanged("tbBarang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPenjualan_tbDetailPenjualan", Storage="_tbPenjualan", ThisKey="ID_Penjualan", OtherKey="ID_Penjualan", IsForeignKey=true)]
		public tbPenjualan tbPenjualan
		{
			get
			{
				return this._tbPenjualan.Entity;
			}
			set
			{
				tbPenjualan previousValue = this._tbPenjualan.Entity;
				if (((previousValue != value) 
							|| (this._tbPenjualan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPenjualan.Entity = null;
						previousValue.tbDetailPenjualans.Remove(this);
					}
					this._tbPenjualan.Entity = value;
					if ((value != null))
					{
						value.tbDetailPenjualans.Add(this);
						this._ID_Penjualan = value.ID_Penjualan;
					}
					else
					{
						this._ID_Penjualan = default(string);
					}
					this.SendPropertyChanged("tbPenjualan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetailRetur")]
	public partial class tbDetailRetur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DetailRetur;
		
		private System.Nullable<int> _Jumlah_Retur;
		
		private string _ID_Retur;
		
		private string _ID_Barang;
		
		private EntityRef<tbBarang> _tbBarang;
		
		private EntityRef<tbRetur> _tbRetur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DetailReturChanging(int value);
    partial void OnID_DetailReturChanged();
    partial void OnJumlah_ReturChanging(System.Nullable<int> value);
    partial void OnJumlah_ReturChanged();
    partial void OnID_ReturChanging(string value);
    partial void OnID_ReturChanged();
    partial void OnID_BarangChanging(string value);
    partial void OnID_BarangChanged();
    #endregion
		
		public tbDetailRetur()
		{
			this._tbBarang = default(EntityRef<tbBarang>);
			this._tbRetur = default(EntityRef<tbRetur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DetailRetur", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DetailRetur
		{
			get
			{
				return this._ID_DetailRetur;
			}
			set
			{
				if ((this._ID_DetailRetur != value))
				{
					this.OnID_DetailReturChanging(value);
					this.SendPropertyChanging();
					this._ID_DetailRetur = value;
					this.SendPropertyChanged("ID_DetailRetur");
					this.OnID_DetailReturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah_Retur", DbType="Int")]
		public System.Nullable<int> Jumlah_Retur
		{
			get
			{
				return this._Jumlah_Retur;
			}
			set
			{
				if ((this._Jumlah_Retur != value))
				{
					this.OnJumlah_ReturChanging(value);
					this.SendPropertyChanging();
					this._Jumlah_Retur = value;
					this.SendPropertyChanged("Jumlah_Retur");
					this.OnJumlah_ReturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Retur", DbType="NChar(10)")]
		public string ID_Retur
		{
			get
			{
				return this._ID_Retur;
			}
			set
			{
				if ((this._ID_Retur != value))
				{
					if (this._tbRetur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ReturChanging(value);
					this.SendPropertyChanging();
					this._ID_Retur = value;
					this.SendPropertyChanged("ID_Retur");
					this.OnID_ReturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Barang", DbType="NChar(10)")]
		public string ID_Barang
		{
			get
			{
				return this._ID_Barang;
			}
			set
			{
				if ((this._ID_Barang != value))
				{
					if (this._tbBarang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_BarangChanging(value);
					this.SendPropertyChanging();
					this._ID_Barang = value;
					this.SendPropertyChanged("ID_Barang");
					this.OnID_BarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbBarang_tbDetailRetur", Storage="_tbBarang", ThisKey="ID_Barang", OtherKey="ID_Barang", IsForeignKey=true)]
		public tbBarang tbBarang
		{
			get
			{
				return this._tbBarang.Entity;
			}
			set
			{
				tbBarang previousValue = this._tbBarang.Entity;
				if (((previousValue != value) 
							|| (this._tbBarang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbBarang.Entity = null;
						previousValue.tbDetailReturs.Remove(this);
					}
					this._tbBarang.Entity = value;
					if ((value != null))
					{
						value.tbDetailReturs.Add(this);
						this._ID_Barang = value.ID_Barang;
					}
					else
					{
						this._ID_Barang = default(string);
					}
					this.SendPropertyChanged("tbBarang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRetur_tbDetailRetur", Storage="_tbRetur", ThisKey="ID_Retur", OtherKey="ID_Retur", IsForeignKey=true)]
		public tbRetur tbRetur
		{
			get
			{
				return this._tbRetur.Entity;
			}
			set
			{
				tbRetur previousValue = this._tbRetur.Entity;
				if (((previousValue != value) 
							|| (this._tbRetur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbRetur.Entity = null;
						previousValue.tbDetailReturs.Remove(this);
					}
					this._tbRetur.Entity = value;
					if ((value != null))
					{
						value.tbDetailReturs.Add(this);
						this._ID_Retur = value.ID_Retur;
					}
					else
					{
						this._ID_Retur = default(string);
					}
					this.SendPropertyChanged("tbRetur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbKaryawan")]
	public partial class tbKaryawan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private string _Nama;
		
		private string _Alamat;
		
		private string _Status;
		
		private System.Nullable<int> _ID_Role;
		
		private EntitySet<tbPembelian> _tbPembelians;
		
		private EntitySet<tbPenjualan> _tbPenjualans;
		
		private EntityRef<tbRole> _tbRole;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNamaChanging(string value);
    partial void OnNamaChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnID_RoleChanging(System.Nullable<int> value);
    partial void OnID_RoleChanged();
    #endregion
		
		public tbKaryawan()
		{
			this._tbPembelians = new EntitySet<tbPembelian>(new Action<tbPembelian>(this.attach_tbPembelians), new Action<tbPembelian>(this.detach_tbPembelians));
			this._tbPenjualans = new EntitySet<tbPenjualan>(new Action<tbPenjualan>(this.attach_tbPenjualans), new Action<tbPenjualan>(this.detach_tbPenjualans));
			this._tbRole = default(EntityRef<tbRole>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama", DbType="NVarChar(50)")]
		public string Nama
		{
			get
			{
				return this._Nama;
			}
			set
			{
				if ((this._Nama != value))
				{
					this.OnNamaChanging(value);
					this.SendPropertyChanging();
					this._Nama = value;
					this.SendPropertyChanged("Nama");
					this.OnNamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Alamat
		{
			get
			{
				return this._Alamat;
			}
			set
			{
				if ((this._Alamat != value))
				{
					this.OnAlamatChanging(value);
					this.SendPropertyChanging();
					this._Alamat = value;
					this.SendPropertyChanged("Alamat");
					this.OnAlamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int")]
		public System.Nullable<int> ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					if (this._tbRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbKaryawan_tbPembelian", Storage="_tbPembelians", ThisKey="Username", OtherKey="Username")]
		public EntitySet<tbPembelian> tbPembelians
		{
			get
			{
				return this._tbPembelians;
			}
			set
			{
				this._tbPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbKaryawan_tbPenjualan", Storage="_tbPenjualans", ThisKey="Username", OtherKey="Username")]
		public EntitySet<tbPenjualan> tbPenjualans
		{
			get
			{
				return this._tbPenjualans;
			}
			set
			{
				this._tbPenjualans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRole_tbKaryawan", Storage="_tbRole", ThisKey="ID_Role", OtherKey="ID_Role", IsForeignKey=true)]
		public tbRole tbRole
		{
			get
			{
				return this._tbRole.Entity;
			}
			set
			{
				tbRole previousValue = this._tbRole.Entity;
				if (((previousValue != value) 
							|| (this._tbRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbRole.Entity = null;
						previousValue.tbKaryawans.Remove(this);
					}
					this._tbRole.Entity = value;
					if ((value != null))
					{
						value.tbKaryawans.Add(this);
						this._ID_Role = value.ID_Role;
					}
					else
					{
						this._ID_Role = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbRole");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbPembelians(tbPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbKaryawan = this;
		}
		
		private void detach_tbPembelians(tbPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbKaryawan = null;
		}
		
		private void attach_tbPenjualans(tbPenjualan entity)
		{
			this.SendPropertyChanging();
			entity.tbKaryawan = this;
		}
		
		private void detach_tbPenjualans(tbPenjualan entity)
		{
			this.SendPropertyChanging();
			entity.tbKaryawan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPembelian")]
	public partial class tbPembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _No_Faktur;
		
		private System.Nullable<System.DateTime> _Tanggal_Pembelian;
		
		private string _CaraBayar;
		
		private string _Salesman;
		
		private System.Nullable<System.DateTime> _JatuhTempo;
		
		private System.Nullable<decimal> _Sub_Total;
		
		private System.Nullable<double> _PPN;
		
		private System.Nullable<decimal> _Total_Pembelian;
		
		private System.Nullable<bool> _Status;
		
		private string _ID_Supplier;
		
		private string _Username;
		
		private EntitySet<tbDetailPembelian> _tbDetailPembelians;
		
		private EntitySet<tbRetur> _tbReturs;
		
		private EntityRef<tbKaryawan> _tbKaryawan;
		
		private EntityRef<tbSupplier> _tbSupplier;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNo_FakturChanging(string value);
    partial void OnNo_FakturChanged();
    partial void OnTanggal_PembelianChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggal_PembelianChanged();
    partial void OnCaraBayarChanging(string value);
    partial void OnCaraBayarChanged();
    partial void OnSalesmanChanging(string value);
    partial void OnSalesmanChanged();
    partial void OnJatuhTempoChanging(System.Nullable<System.DateTime> value);
    partial void OnJatuhTempoChanged();
    partial void OnSub_TotalChanging(System.Nullable<decimal> value);
    partial void OnSub_TotalChanged();
    partial void OnPPNChanging(System.Nullable<double> value);
    partial void OnPPNChanged();
    partial void OnTotal_PembelianChanging(System.Nullable<decimal> value);
    partial void OnTotal_PembelianChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnID_SupplierChanging(string value);
    partial void OnID_SupplierChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public tbPembelian()
		{
			this._tbDetailPembelians = new EntitySet<tbDetailPembelian>(new Action<tbDetailPembelian>(this.attach_tbDetailPembelians), new Action<tbDetailPembelian>(this.detach_tbDetailPembelians));
			this._tbReturs = new EntitySet<tbRetur>(new Action<tbRetur>(this.attach_tbReturs), new Action<tbRetur>(this.detach_tbReturs));
			this._tbKaryawan = default(EntityRef<tbKaryawan>);
			this._tbSupplier = default(EntityRef<tbSupplier>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Faktur", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string No_Faktur
		{
			get
			{
				return this._No_Faktur;
			}
			set
			{
				if ((this._No_Faktur != value))
				{
					this.OnNo_FakturChanging(value);
					this.SendPropertyChanging();
					this._No_Faktur = value;
					this.SendPropertyChanged("No_Faktur");
					this.OnNo_FakturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal_Pembelian", DbType="Date")]
		public System.Nullable<System.DateTime> Tanggal_Pembelian
		{
			get
			{
				return this._Tanggal_Pembelian;
			}
			set
			{
				if ((this._Tanggal_Pembelian != value))
				{
					this.OnTanggal_PembelianChanging(value);
					this.SendPropertyChanging();
					this._Tanggal_Pembelian = value;
					this.SendPropertyChanged("Tanggal_Pembelian");
					this.OnTanggal_PembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaraBayar", DbType="NVarChar(50)")]
		public string CaraBayar
		{
			get
			{
				return this._CaraBayar;
			}
			set
			{
				if ((this._CaraBayar != value))
				{
					this.OnCaraBayarChanging(value);
					this.SendPropertyChanging();
					this._CaraBayar = value;
					this.SendPropertyChanged("CaraBayar");
					this.OnCaraBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salesman", DbType="NVarChar(50)")]
		public string Salesman
		{
			get
			{
				return this._Salesman;
			}
			set
			{
				if ((this._Salesman != value))
				{
					this.OnSalesmanChanging(value);
					this.SendPropertyChanging();
					this._Salesman = value;
					this.SendPropertyChanged("Salesman");
					this.OnSalesmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JatuhTempo", DbType="Date")]
		public System.Nullable<System.DateTime> JatuhTempo
		{
			get
			{
				return this._JatuhTempo;
			}
			set
			{
				if ((this._JatuhTempo != value))
				{
					this.OnJatuhTempoChanging(value);
					this.SendPropertyChanging();
					this._JatuhTempo = value;
					this.SendPropertyChanged("JatuhTempo");
					this.OnJatuhTempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="Money")]
		public System.Nullable<decimal> Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this.OnSub_TotalChanging(value);
					this.SendPropertyChanging();
					this._Sub_Total = value;
					this.SendPropertyChanged("Sub_Total");
					this.OnSub_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPN", DbType="Float")]
		public System.Nullable<double> PPN
		{
			get
			{
				return this._PPN;
			}
			set
			{
				if ((this._PPN != value))
				{
					this.OnPPNChanging(value);
					this.SendPropertyChanging();
					this._PPN = value;
					this.SendPropertyChanged("PPN");
					this.OnPPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Pembelian", DbType="Money")]
		public System.Nullable<decimal> Total_Pembelian
		{
			get
			{
				return this._Total_Pembelian;
			}
			set
			{
				if ((this._Total_Pembelian != value))
				{
					this.OnTotal_PembelianChanging(value);
					this.SendPropertyChanging();
					this._Total_Pembelian = value;
					this.SendPropertyChanged("Total_Pembelian");
					this.OnTotal_PembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Supplier", DbType="NChar(10)")]
		public string ID_Supplier
		{
			get
			{
				return this._ID_Supplier;
			}
			set
			{
				if ((this._ID_Supplier != value))
				{
					if (this._tbSupplier.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SupplierChanging(value);
					this.SendPropertyChanging();
					this._ID_Supplier = value;
					this.SendPropertyChanged("ID_Supplier");
					this.OnID_SupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(15)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._tbKaryawan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPembelian_tbDetailPembelian", Storage="_tbDetailPembelians", ThisKey="No_Faktur", OtherKey="No_Faktur")]
		public EntitySet<tbDetailPembelian> tbDetailPembelians
		{
			get
			{
				return this._tbDetailPembelians;
			}
			set
			{
				this._tbDetailPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPembelian_tbRetur", Storage="_tbReturs", ThisKey="No_Faktur", OtherKey="No_Faktur")]
		public EntitySet<tbRetur> tbReturs
		{
			get
			{
				return this._tbReturs;
			}
			set
			{
				this._tbReturs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbKaryawan_tbPembelian", Storage="_tbKaryawan", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public tbKaryawan tbKaryawan
		{
			get
			{
				return this._tbKaryawan.Entity;
			}
			set
			{
				tbKaryawan previousValue = this._tbKaryawan.Entity;
				if (((previousValue != value) 
							|| (this._tbKaryawan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbKaryawan.Entity = null;
						previousValue.tbPembelians.Remove(this);
					}
					this._tbKaryawan.Entity = value;
					if ((value != null))
					{
						value.tbPembelians.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("tbKaryawan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSupplier_tbPembelian", Storage="_tbSupplier", ThisKey="ID_Supplier", OtherKey="ID_Supplier", IsForeignKey=true)]
		public tbSupplier tbSupplier
		{
			get
			{
				return this._tbSupplier.Entity;
			}
			set
			{
				tbSupplier previousValue = this._tbSupplier.Entity;
				if (((previousValue != value) 
							|| (this._tbSupplier.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSupplier.Entity = null;
						previousValue.tbPembelians.Remove(this);
					}
					this._tbSupplier.Entity = value;
					if ((value != null))
					{
						value.tbPembelians.Add(this);
						this._ID_Supplier = value.ID_Supplier;
					}
					else
					{
						this._ID_Supplier = default(string);
					}
					this.SendPropertyChanged("tbSupplier");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetailPembelians(tbDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbPembelian = this;
		}
		
		private void detach_tbDetailPembelians(tbDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.tbPembelian = null;
		}
		
		private void attach_tbReturs(tbRetur entity)
		{
			this.SendPropertyChanging();
			entity.tbPembelian = this;
		}
		
		private void detach_tbReturs(tbRetur entity)
		{
			this.SendPropertyChanging();
			entity.tbPembelian = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPenjualan")]
	public partial class tbPenjualan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Penjualan;
		
		private System.Nullable<System.DateTime> _Tanggal_Penjualan;
		
		private System.Nullable<decimal> _Total_Penjualan;
		
		private string _Username;
		
		private EntitySet<tbDetailPenjualan> _tbDetailPenjualans;
		
		private EntityRef<tbKaryawan> _tbKaryawan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PenjualanChanging(string value);
    partial void OnID_PenjualanChanged();
    partial void OnTanggal_PenjualanChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggal_PenjualanChanged();
    partial void OnTotal_PenjualanChanging(System.Nullable<decimal> value);
    partial void OnTotal_PenjualanChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    #endregion
		
		public tbPenjualan()
		{
			this._tbDetailPenjualans = new EntitySet<tbDetailPenjualan>(new Action<tbDetailPenjualan>(this.attach_tbDetailPenjualans), new Action<tbDetailPenjualan>(this.detach_tbDetailPenjualans));
			this._tbKaryawan = default(EntityRef<tbKaryawan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Penjualan", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Penjualan
		{
			get
			{
				return this._ID_Penjualan;
			}
			set
			{
				if ((this._ID_Penjualan != value))
				{
					this.OnID_PenjualanChanging(value);
					this.SendPropertyChanging();
					this._ID_Penjualan = value;
					this.SendPropertyChanged("ID_Penjualan");
					this.OnID_PenjualanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal_Penjualan", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tanggal_Penjualan
		{
			get
			{
				return this._Tanggal_Penjualan;
			}
			set
			{
				if ((this._Tanggal_Penjualan != value))
				{
					this.OnTanggal_PenjualanChanging(value);
					this.SendPropertyChanging();
					this._Tanggal_Penjualan = value;
					this.SendPropertyChanged("Tanggal_Penjualan");
					this.OnTanggal_PenjualanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Penjualan", DbType="Money")]
		public System.Nullable<decimal> Total_Penjualan
		{
			get
			{
				return this._Total_Penjualan;
			}
			set
			{
				if ((this._Total_Penjualan != value))
				{
					this.OnTotal_PenjualanChanging(value);
					this.SendPropertyChanging();
					this._Total_Penjualan = value;
					this.SendPropertyChanged("Total_Penjualan");
					this.OnTotal_PenjualanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(15)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._tbKaryawan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPenjualan_tbDetailPenjualan", Storage="_tbDetailPenjualans", ThisKey="ID_Penjualan", OtherKey="ID_Penjualan")]
		public EntitySet<tbDetailPenjualan> tbDetailPenjualans
		{
			get
			{
				return this._tbDetailPenjualans;
			}
			set
			{
				this._tbDetailPenjualans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbKaryawan_tbPenjualan", Storage="_tbKaryawan", ThisKey="Username", OtherKey="Username", IsForeignKey=true)]
		public tbKaryawan tbKaryawan
		{
			get
			{
				return this._tbKaryawan.Entity;
			}
			set
			{
				tbKaryawan previousValue = this._tbKaryawan.Entity;
				if (((previousValue != value) 
							|| (this._tbKaryawan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbKaryawan.Entity = null;
						previousValue.tbPenjualans.Remove(this);
					}
					this._tbKaryawan.Entity = value;
					if ((value != null))
					{
						value.tbPenjualans.Add(this);
						this._Username = value.Username;
					}
					else
					{
						this._Username = default(string);
					}
					this.SendPropertyChanged("tbKaryawan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetailPenjualans(tbDetailPenjualan entity)
		{
			this.SendPropertyChanging();
			entity.tbPenjualan = this;
		}
		
		private void detach_tbDetailPenjualans(tbDetailPenjualan entity)
		{
			this.SendPropertyChanging();
			entity.tbPenjualan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbRetur")]
	public partial class tbRetur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Retur;
		
		private System.Nullable<System.DateTime> _Tanggal_Retur;
		
		private string _No_Faktur;
		
		private EntitySet<tbDetailRetur> _tbDetailReturs;
		
		private EntityRef<tbPembelian> _tbPembelian;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ReturChanging(string value);
    partial void OnID_ReturChanged();
    partial void OnTanggal_ReturChanging(System.Nullable<System.DateTime> value);
    partial void OnTanggal_ReturChanged();
    partial void OnNo_FakturChanging(string value);
    partial void OnNo_FakturChanged();
    #endregion
		
		public tbRetur()
		{
			this._tbDetailReturs = new EntitySet<tbDetailRetur>(new Action<tbDetailRetur>(this.attach_tbDetailReturs), new Action<tbDetailRetur>(this.detach_tbDetailReturs));
			this._tbPembelian = default(EntityRef<tbPembelian>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Retur", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Retur
		{
			get
			{
				return this._ID_Retur;
			}
			set
			{
				if ((this._ID_Retur != value))
				{
					this.OnID_ReturChanging(value);
					this.SendPropertyChanging();
					this._ID_Retur = value;
					this.SendPropertyChanged("ID_Retur");
					this.OnID_ReturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanggal_Retur", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tanggal_Retur
		{
			get
			{
				return this._Tanggal_Retur;
			}
			set
			{
				if ((this._Tanggal_Retur != value))
				{
					this.OnTanggal_ReturChanging(value);
					this.SendPropertyChanging();
					this._Tanggal_Retur = value;
					this.SendPropertyChanged("Tanggal_Retur");
					this.OnTanggal_ReturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Faktur", DbType="NVarChar(20)")]
		public string No_Faktur
		{
			get
			{
				return this._No_Faktur;
			}
			set
			{
				if ((this._No_Faktur != value))
				{
					if (this._tbPembelian.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNo_FakturChanging(value);
					this.SendPropertyChanging();
					this._No_Faktur = value;
					this.SendPropertyChanged("No_Faktur");
					this.OnNo_FakturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRetur_tbDetailRetur", Storage="_tbDetailReturs", ThisKey="ID_Retur", OtherKey="ID_Retur")]
		public EntitySet<tbDetailRetur> tbDetailReturs
		{
			get
			{
				return this._tbDetailReturs;
			}
			set
			{
				this._tbDetailReturs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPembelian_tbRetur", Storage="_tbPembelian", ThisKey="No_Faktur", OtherKey="No_Faktur", IsForeignKey=true)]
		public tbPembelian tbPembelian
		{
			get
			{
				return this._tbPembelian.Entity;
			}
			set
			{
				tbPembelian previousValue = this._tbPembelian.Entity;
				if (((previousValue != value) 
							|| (this._tbPembelian.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPembelian.Entity = null;
						previousValue.tbReturs.Remove(this);
					}
					this._tbPembelian.Entity = value;
					if ((value != null))
					{
						value.tbReturs.Add(this);
						this._No_Faktur = value.No_Faktur;
					}
					else
					{
						this._No_Faktur = default(string);
					}
					this.SendPropertyChanged("tbPembelian");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbDetailReturs(tbDetailRetur entity)
		{
			this.SendPropertyChanging();
			entity.tbRetur = this;
		}
		
		private void detach_tbDetailReturs(tbDetailRetur entity)
		{
			this.SendPropertyChanging();
			entity.tbRetur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbRole")]
	public partial class tbRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Role;
		
		private string _Nama_Role;
		
		private EntitySet<tbKaryawan> _tbKaryawans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RoleChanging(int value);
    partial void OnID_RoleChanged();
    partial void OnNama_RoleChanging(string value);
    partial void OnNama_RoleChanged();
    #endregion
		
		public tbRole()
		{
			this._tbKaryawans = new EntitySet<tbKaryawan>(new Action<tbKaryawan>(this.attach_tbKaryawans), new Action<tbKaryawan>(this.detach_tbKaryawans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Role
		{
			get
			{
				return this._ID_Role;
			}
			set
			{
				if ((this._ID_Role != value))
				{
					this.OnID_RoleChanging(value);
					this.SendPropertyChanging();
					this._ID_Role = value;
					this.SendPropertyChanged("ID_Role");
					this.OnID_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Role", DbType="NVarChar(50)")]
		public string Nama_Role
		{
			get
			{
				return this._Nama_Role;
			}
			set
			{
				if ((this._Nama_Role != value))
				{
					this.OnNama_RoleChanging(value);
					this.SendPropertyChanging();
					this._Nama_Role = value;
					this.SendPropertyChanged("Nama_Role");
					this.OnNama_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbRole_tbKaryawan", Storage="_tbKaryawans", ThisKey="ID_Role", OtherKey="ID_Role")]
		public EntitySet<tbKaryawan> tbKaryawans
		{
			get
			{
				return this._tbKaryawans;
			}
			set
			{
				this._tbKaryawans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbKaryawans(tbKaryawan entity)
		{
			this.SendPropertyChanging();
			entity.tbRole = this;
		}
		
		private void detach_tbKaryawans(tbKaryawan entity)
		{
			this.SendPropertyChanging();
			entity.tbRole = null;
		}
	}
}
#pragma warning restore 1591
